### ISSUE TITLE
Issue with multiprocessing

### ISSUE THREAD

**Issue by dcramer** [dcramer/taskmaster#1]
In a certain case, which we've yet to identify, multiprocessing is failing on the handshake.

We get this error reported back to the slave:

  $ tm-slave [omitted]
  Traceback (most recent call last):
    File "/Users/dcramer/.virtualenvs/disqus/bin/tm-slave", line 9, in <module>
      load_entry_point('taskmaster==0.3.0', 'console_scripts', 'tm-slave')()
    File "/Users/dcramer/Development/taskmaster/src/taskmaster/cli/slave.py", line 50, in main
      sys.exit(run(args[0], **options.**dict**))
    File "/Users/dcramer/Development/taskmaster/src/taskmaster/cli/slave.py", line 25, in run
      m.connect()
    File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/multiprocessing/managers.py", line 474, in connect
      conn = Client(self._address, authkey=self._authkey)
    File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/multiprocessing/connection.py", line 150, in Client
      deliver_challenge(c, authkey)
    File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/multiprocessing/connection.py", line 374, in deliver_challenge
      response = connection.recv_bytes(256)        # reject large message
  IOError: bad message length

Digging into this a little bit more, the recv_bytes call was raising a socket error (35) which means EAGAIN. After adding the retry, we hit yet another error further in:

  $ tm-slave disqus.scripts.migrate_post_to_partitionedpost
  Traceback (most recent call last):
    File "/Users/dcramer/.virtualenvs/disqus/bin/tm-slave", line 9, in <module>
      load_entry_point('taskmaster==0.3.0', 'console_scripts', 'tm-slave')()
    File "/Users/dcramer/Development/taskmaster/src/taskmaster/cli/slave.py", line 50, in main
      sys.exit(run(args[0], **options.**dict**))
    File "/Users/dcramer/Development/taskmaster/src/taskmaster/cli/slave.py", line 25, in run
      m.connect()
    File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/multiprocessing/managers.py", line 474, in connect
      conn = Client(self._address, authkey=self._authkey)
    File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/multiprocessing/connection.py", line 149, in Client
      answer_challenge(c, authkey)
    File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/multiprocessing/connection.py", line 391, in answer_challenge
      response = connection.recv_bytes(256)        # reject large message
  EOFError

The only conclusion is that the socket is somehow not configured correctly. This doesnt happen in our tests, and it only happens when the disqus application gets imported (which can be a large amount of Python code).

**Comment by dcramer** [comment]
Digging into this more the problem seems to be with **somewhere** in the codebase calling setdefaulttimeout

Adding socket.setdefaultimeout(None) after the disqus app is imported corrects the above behavior

**Comment by dcramer** [comment]
I believe we solved this when we switched to zeromq
