### ISSUE TITLE
it seems that progressbar have changed :

### ISSUE THREAD

**Issue by bussiere** [dcramer/taskmaster#8]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/taskmaster/cli/master.py", line 19, in run
    controller = Controller(server, target, kwargs=kwargs, log_level=log_level)
  File "/usr/local/lib/python2.7/dist-packages/taskmaster/server.py", line 139, in __init__
    self.pbar = self.get_progressbar()
  File "/usr/local/lib/python2.7/dist-packages/taskmaster/server.py", line 145, in get_progressbar
    from taskmaster.progressbar import Counter, Speed, Timer, ProgressBar, UnknownLength, Value
  File "/usr/local/lib/python2.7/dist-packages/taskmaster/progressbar.py", line 11, in <module>
    from progressbar import ProgressBar, UnknownLength, Counter, Timer
ImportError: cannot import name UnknownLength
No response from server; shutting down.

**Comment by ecarreras** [comment]
I've tried it and it seems correct:

``` sh
$ mktmpenv
$ pip install progressbar
$ python -c "from progressbar import ProgressBar, UnknownLength, Counter, Timer"
```

Do you have the last version of progressbar?
